name: Garbage collection
concurrency:
  group: cache-the-planet-main-writes
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      dry-run:
        { description: Dry run, required: false, default: true, type: boolean }
  schedule: [{ cron: "0 3 * * *" }]
jobs:
  gc:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: node dist/gc.js --dry-run
        env:
          CACHE_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run || 'true' }}
