name: Test
run-name: Test - ${{ github.event_name }}${{ github.event_name == 'workflow_run' && format(' ({0})', github.event.workflow_run.name) || '' }}
on:
  push:
  pull_request:
  workflow_run:
    workflows:
      - Build action distribution
      - Docker cache integration
      - Node cache asset integration
      - uv cache asset integration
      - uv Python cache asset integration
      - Task cache asset integration
      - Java cache asset integration
      - Gradle cache asset integration
    types: [completed]
jobs:
  unit:
    name: Unit tests
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          ref: ${{ github.event_name == 'workflow_run' && 'main' || github.ref }}
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm install
      - run: npm run test
      - run: bash tests/run.sh
